-- Migration: Update embedding dimensions to 1536 (OpenAI text-embedding-3-small)
-- Reason: Using OpenAI embeddings for consistent, high-quality semantic search
-- Date: 2025-11-12 (Updated from 768 to 1536)

BEGIN;

-- Step 1: Drop the existing embedding column
ALTER TABLE memories DROP COLUMN IF EXISTS embedding;

-- Step 2: Add embedding column with 1536 dimensions for OpenAI
ALTER TABLE memories ADD COLUMN embedding vector(1536);

-- Step 3: Create index for vector similarity search
CREATE INDEX IF NOT EXISTS idx_memories_embedding ON memories
USING ivfflat (embedding vector_cosine_ops)
WITH (lists = 100);

-- Step 4: Verify the change
DO $$
DECLARE
    dims integer;
BEGIN
    SELECT atttypmod INTO dims
    FROM pg_attribute
    WHERE attrelid = 'memories'::regclass
    AND attname = 'embedding';

    IF dims = 1536 THEN
        RAISE NOTICE '✅ Embedding dimension successfully updated to 1536';
    ELSE
        RAISE EXCEPTION '❌ Embedding dimension is %, expected 1536', dims;
    END IF;
END $$;

COMMIT;

-- Summary:
-- ✅ Embedding column now supports 1536-dimensional vectors (OpenAI text-embedding-3-small)
-- ✅ Vector similarity index created for fast semantic search
-- ⚠️  All existing embeddings have been cleared (will be regenerated by backfill)
