'use client';

import { useState } from 'react';
import { X, Wand2, Download, Check, ChevronRight } from 'lucide-react';
import { useAppStore } from '@/lib/store';

const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3010';

interface CoworkModalProps {
  onClose: () => void;
}

type Step = 1 | 2 | 3;

const WORK_STYLES = [
  'Outcome-focused — I give direction, need execution',
  'Collaborative — I like to think out loud together',
  'Structured — Follow the process exactly, no improvisation',
  'Flexible — Use judgment, surface surprises',
];

const COMM_PREFS = [
  'Async-first (Loom/Slack, avoid live calls)',
  'Short check-ins only (under 15 min)',
  'Daily standup style',
  'Weekly review cadence',
];

export function CoworkModal({ onClose }: CoworkModalProps) {
  const user = useAppStore(s => s.user);
  const [step, setStep] = useState<Step>(1);
  const [generating, setGenerating] = useState(false);
  const [generated, setGenerated] = useState('');
  const [downloading, setDownloading] = useState(false);
  const [downloaded, setDownloaded] = useState(false);

  const [form, setForm] = useState({
    name: user?.name || user?.email?.split('@')[0] || '',
    coachingNiche: '',
    workStyle: '',
    commPref: '',
    priorities: '',
    doNotDo: '',
  });

  const updateForm = (key: keyof typeof form, val: string) =>
    setForm(prev => ({ ...prev, [key]: val }));

  const generate = async () => {
    setGenerating(true);
    try {
      const token = localStorage.getItem('accessToken');
      const prompt = `Generate a concise, professional "Working with ${form.name}" instruction guide for a VA or EA.

About this person:
- Name: ${form.name}
- Coaching niche: ${form.coachingNiche}
- Work style: ${form.workStyle}
- Communication preference: ${form.commPref}
- Top weekly priorities: ${form.priorities}
- What NOT to do / common mistakes: ${form.doNotDo}

Format the guide with these sections:
1. About [Name] — who they are and what they do (2-3 sentences)
2. How They Like to Work — decision-making style, delegation preferences
3. Communication Rules — response times, preferred channels, meeting cadence
4. Your Weekly Priorities — the 3-5 things that matter most each week
5. What Good Work Looks Like — specific examples of what success means
6. What to Avoid — common mistakes, pet peeves, hard no's
7. How to Handle Decisions — what to bring to them vs handle independently
8. Tools & Access — note any tools they should know about

Keep it practical, specific, and under 600 words. Write in second person ("You will..." "When [Name] asks...").`;

      const r = await fetch(`${API}/api/agent/call`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
        body: JSON.stringify({
          agentId: 'mindset-score',  // Use any available agent for generation
          message: prompt,
          systemOverride: 'You are a professional business writer. Generate a clear, actionable working guide. No preamble. Start directly with "# Working with [Name]".',
        }),
      });

      if (r.ok) {
        const data = await r.json();
        setGenerated(data.response || data.content || data.text || '');
      } else {
        // Fallback template if API fails
        setGenerated(generateFallback());
      }
    } catch {
      setGenerated(generateFallback());
    }
    setGenerating(false);
    setStep(3);
  };

  const generateFallback = () => `# Working with ${form.name}

## About ${form.name}
${form.name} is a ${form.coachingNiche} coach who helps clients transform their mindset and results. They work with entrepreneurs and high-performers who want to think more clearly and act more decisively.

## How They Like to Work
${form.workStyle}. They delegate with clear outcomes in mind and expect you to surface blockers early — don't wait until a deadline to flag a problem.

## Communication Rules
${form.commPref}. Match their energy: brief and direct. Use bullet points over paragraphs. Always lead with the most important thing.

## Your Weekly Priorities
${form.priorities}

## What to Avoid
${form.doNotDo}

## How to Handle Decisions
Bring decisions to ${form.name} when they involve: client relationships, money over $500, anything public-facing, or anything that would take more than 2 hours to undo. Handle everything else using your best judgment and log what you did.

---
*Generated by MindsetOS Cowork Generator*`;

  const downloadDocx = async () => {
    setDownloading(true);
    try {
      const { Document, Paragraph, TextRun, HeadingLevel, Packer } = await import('docx');
      const lines = generated.split('\n');
      const paragraphs: InstanceType<typeof Paragraph>[] = [];

      for (const line of lines) {
        if (line.startsWith('# ')) {
          paragraphs.push(new Paragraph({ text: line.slice(2), heading: HeadingLevel.HEADING_1 }));
        } else if (line.startsWith('## ')) {
          paragraphs.push(new Paragraph({ text: line.slice(3), heading: HeadingLevel.HEADING_2 }));
        } else if (line.startsWith('- ')) {
          paragraphs.push(new Paragraph({ text: line.slice(2).replace(/\*\*(.*?)\*\*/g, '$1'), bullet: { level: 0 } }));
        } else if (line.trim() === '') {
          paragraphs.push(new Paragraph({ text: '' }));
        } else {
          paragraphs.push(new Paragraph({ children: [new TextRun(line.replace(/\*\*(.*?)\*\*/g, '$1').replace(/\*(.*?)\*/g, '$1'))] }));
        }
      }

      const doc = new Document({ sections: [{ properties: {}, children: paragraphs }] });
      const buffer = await Packer.toBuffer(doc);
      const blob = new Blob([new Uint8Array(buffer)], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `working-with-${(form.name || 'me').toLowerCase().replace(/\s+/g, '-')}.docx`;
      a.click();
      URL.revokeObjectURL(url);
      setDownloaded(true);
      setTimeout(() => setDownloaded(false), 3000);
    } catch (err) {
      console.error('[CoworkModal] DOCX export failed:', err);
    }
    setDownloading(false);
  };

  const copyText = () => {
    navigator.clipboard.writeText(generated).then(() => {
      setDownloaded(true);
      setTimeout(() => setDownloaded(false), 2000);
    }).catch((err: unknown) => {
      console.error('[CoworkModal] Failed to copy to clipboard:', err);
      // Fallback: still show the button briefly so user can manually copy
      setDownloaded(false);
    });
  };

  return (
    /* z-[9999]: highest-priority modal — sits above TrialExpiredPopup (z-[9999]) and all other overlays */
    <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4" onClick={onClose}>
      <div
        className="bg-white dark:bg-gray-900 rounded-2xl shadow-2xl w-full max-w-xl overflow-hidden"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200 dark:border-gray-800">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-indigo-100 dark:bg-indigo-900/40 flex items-center justify-center">
              <Wand2 className="w-4 h-4 text-indigo-600 dark:text-indigo-400" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-gray-900 dark:text-white">Cowork Instruction Generator</h2>
              <p className="text-xs text-gray-500 dark:text-gray-400">Step {step} of 3</p>
            </div>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors">
            <X className="w-4 h-4 text-gray-500" />
          </button>
        </div>

        {/* Step progress */}
        <div className="flex gap-1 px-6 pt-4">
          {([1, 2, 3] as Step[]).map(s => (
            <div key={s} className={`flex-1 h-1 rounded-full transition-colors ${s <= step ? 'bg-indigo-500' : 'bg-gray-200 dark:bg-gray-700'}`} />
          ))}
        </div>

        {/* Step 1: About you */}
        {step === 1 && (
          <div className="px-6 py-5 space-y-4">
            <div>
              <p className="text-sm font-semibold text-gray-900 dark:text-white mb-1">Who are you?</p>
              <p className="text-xs text-gray-500 dark:text-gray-400 mb-3">This becomes the guide your VA follows.</p>
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">Your name</label>
              <input
                value={form.name}
                onChange={e => updateForm('name', e.target.value)}
                placeholder="Greg"
                className="w-full px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">Your coaching niche</label>
              <input
                value={form.coachingNiche}
                onChange={e => updateForm('coachingNiche', e.target.value)}
                placeholder="Mindset coaching for entrepreneurs"
                className="w-full px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
              />
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">Top weekly priorities</label>
              <textarea
                value={form.priorities}
                onChange={e => updateForm('priorities', e.target.value)}
                rows={3}
                placeholder="Recording podcast content, client sessions, outreach to 5 new leads, newsletter..."
                className="w-full px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-500 focus:border-transparent resize-none"
              />
            </div>
            <button
              onClick={() => setStep(2)}
              disabled={!form.name || !form.coachingNiche}
              className="w-full flex items-center justify-center gap-2 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium rounded-lg disabled:opacity-40 transition-colors"
            >
              Next <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        )}

        {/* Step 2: Working style */}
        {step === 2 && (
          <div className="px-6 py-5 space-y-4">
            <div>
              <p className="text-sm font-semibold text-gray-900 dark:text-white mb-1">How you like to work</p>
              <p className="text-xs text-gray-500 dark:text-gray-400 mb-3">This shapes how your VA should approach their work.</p>
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-2">Work style</label>
              <div className="space-y-2">
                {WORK_STYLES.map(s => (
                  <button
                    key={s}
                    onClick={() => updateForm('workStyle', s)}
                    className={`w-full text-left px-3 py-2.5 rounded-lg border text-sm transition-colors ${
                      form.workStyle === s
                        ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-900/20 text-indigo-700 dark:text-indigo-300'
                        : 'border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-300 hover:border-gray-300 dark:hover:border-gray-600'
                    }`}
                  >
                    {s}
                  </button>
                ))}
              </div>
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-2">Communication preference</label>
              <div className="space-y-2">
                {COMM_PREFS.map(c => (
                  <button
                    key={c}
                    onClick={() => updateForm('commPref', c)}
                    className={`w-full text-left px-3 py-2.5 rounded-lg border text-sm transition-colors ${
                      form.commPref === c
                        ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-900/20 text-indigo-700 dark:text-indigo-300'
                        : 'border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-300 hover:border-gray-300 dark:hover:border-gray-600'
                    }`}
                  >
                    {c}
                  </button>
                ))}
              </div>
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-600 dark:text-gray-400 mb-1">What NOT to do (pet peeves, hard no's)</label>
              <textarea
                value={form.doNotDo}
                onChange={e => updateForm('doNotDo', e.target.value)}
                rows={2}
                placeholder="Don't send emails without my review, don't reschedule clients without asking, don't use jargon..."
                className="w-full px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-indigo-500 focus:border-transparent resize-none"
              />
            </div>
            <div className="flex gap-2">
              <button
                onClick={() => setStep(1)}
                className="px-4 py-2.5 border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 text-sm font-medium rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
              >
                Back
              </button>
              <button
                onClick={generate}
                disabled={!form.workStyle || !form.commPref || generating}
                className="flex-1 flex items-center justify-center gap-2 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium rounded-lg disabled:opacity-40 transition-colors"
              >
                {generating ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Wand2 className="w-4 h-4" />
                    Generate Guide
                  </>
                )}
              </button>
            </div>
          </div>
        )}

        {/* Step 3: Generated result */}
        {step === 3 && (
          <div className="px-6 py-5 space-y-4">
            <div>
              <p className="text-sm font-semibold text-gray-900 dark:text-white mb-1">Your cowork guide is ready</p>
              <p className="text-xs text-gray-500 dark:text-gray-400">Share this with your VA or EA. Edit as needed.</p>
            </div>
            <div className="max-h-64 overflow-y-auto rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50 p-4">
              <pre className="text-xs text-gray-700 dark:text-gray-300 whitespace-pre-wrap font-mono leading-relaxed">
                {generated}
              </pre>
            </div>
            <div className="flex gap-2">
              <button
                onClick={copyText}
                className="flex-1 flex items-center justify-center gap-2 py-2.5 border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 text-sm font-medium rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
              >
                {downloaded ? <Check className="w-4 h-4 text-green-500" /> : <span>Copy Text</span>}
              </button>
              <button
                onClick={downloadDocx}
                disabled={downloading}
                className="flex-1 flex items-center justify-center gap-2 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium rounded-lg disabled:opacity-50 transition-colors"
              >
                {downloading ? (
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  <>
                    <Download className="w-4 h-4" />
                    Download .docx
                  </>
                )}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
